# Generated by Django 5.1 on 2024-08-15 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_tickets', models.PositiveIntegerField()),
                ('prizes', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('participant_ip', models.GenericIPAddressField()),
                ('verification_code', models.CharField(max_length=64)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='raffles.raffle')),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.CharField(max_length=100)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='raffles.raffle')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raffles.ticket')),
            ],
        ),
    ]
